name: Deploy to VPS

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key phuong1404@34.125.134.251 << 'EOF'
          cd server
          git pull origin master
          npm install
          npm run serve &
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
