name: Deploy Client to VPS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'

jobs:
  deploy_client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan your_vps_ip >> ~/.ssh/known_hosts

    - name: Deploy Client to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa user@your_vps_ip << 'EOF'
          cd client
          git pull origin ${{ github.event.inputs.branch }}
          npm install
          npm run start &
        EOF
